project:
  type: website
  output-dir: docs

website:
  title: "Theo Gibbs"
  search: false
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - research.qmd
      - publications.qmd
      - outreach.qmd
      - CV.qmd
    logo: "hoi.png"
    right:
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=XEGAFg0AAAAJ&hl=en
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-1515-8420
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/theogibbs.bsky.social 

    tools:
      - icon: github
        href: https://github.com/theogibbs
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

