---
title: "Publications"
---

If you have trouble accessing any of them or would like a copy, please feel free to email me. My papers are also available through <a href="https://scholar.google.com/citations?user=XEGAFg0AAAAJ&hl=en"> Google Scholar</a>.

### Preprints

-   Gibbs, T.\*, Gold, Z.\*, Oyler, H., Levine, J. & Kraft, N. [Spatial clustering reveals the impact of higher-order interactions in a diverse annual plant community.](https://www.biorxiv.org/content/10.1101/2025.07.14.664706v1.abstract) (2025). (\* denotes equal contribution).

-   Gibbs, T.\*, Mazzarisi, O.\*, Fant, L., An, R., Grilli, J., Barabás, G. †, & Song, C. † [Label invariance: a guiding principle for ecological models.](https://www.biorxiv.org/content/10.1101/2025.07.15.664968v1) (2025). (\* and † denote equal contribution).

-   Gibbs, T., Dahlin, K., Brennan, J., Silveira, C.\* & McManus, L.\* [Coexistence of bacteria with a competition-colonization tradeoff on a dynamic coral host.](https://www.biorxiv.org/content/10.1101/2024.09.15.612558v1) (2024). (\* denotes equal contribution).

### Published Work

-   Gibbs, T., Levine, J. & Turcotte, M. [Competitor-induced plasticity modifies the interactions and predicted competitive outcomes between annual plants.](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.70085) Ecology (2025).

-   Gibbs, T., Gellner, G., Levin, S., McCann, K., Hastings, A., & Levine, J. [When can higher-order interactions produce stable coexistence?](https://onlinelibrary.wiley.com/doi/10.1111/ele.14458) Ecology Letters (2024).

-   Gibbs, T., Levin, S. & Levine, J. [Coexistence in diverse communities with higher-order interactions.](https://www.pnas.org/doi/10.1073/pnas.2205063119) Proceedings of the National Academy of Sciences (2022).

-   Gibbs, T., Zhang, Y., Miller, Z. & O’Dwyer, J. [Stability criteria for the consumption and exchange of essential resources.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010521) PLoS Computational Biology (2022).

-   Yamamichi, M., Gibbs, T., & Levine, J. [Integrating eco-evolutionary dynamics and modern coexistence theory.](https://onlinelibrary.wiley.com/doi/full/10.1111/ele.14078) Ecology Letters (2022).

-   Levine, J., Levine, J., Gibbs, T. & Pacala, S. [Competition for water and species coexistence in phenologically structured annual plant communities.](https://onlinelibrary.wiley.com/doi/10.1111/ele.13990) Ecology Letters (2022).

-   D’Andrea, R.\*, Gibbs, T.\* & O’Dwyer, J. [Emergent neutrality in consumer-resource dynamics.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008102) PLoS Computational Biology (2020). (\* denotes equal contribution).

-   Gibbs, T., Grilli, J., Rogers, T., & Allesina, S. [Effect of population abundances on the stability of large random ecosystems.](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.98.022410) Physical Review E (2018).
